name: pink_lady
channels:
 - conda-forge
dependencies:
  - python==3.10.*
  - gdal
  - numpy
  - pylint
  - pytest
  - conda-forge:pytest-shutil
  - flake8
  - sphinx
  - conda-forge:furo
  - conda-forge:importlib-resources
  - dataclasses
  - conda-forge:jsons
  - pyproj
  - scipy
