name: borea
channels:
 - conda-forge
dependencies:
  - python>=3.9.*
  - gdal>=3.3.2
  - numpy<= 1.26.4
  - pylint
  - pytest
  - conda-forge:pytest-shutil
  - flake8
  - sphinx
  - conda-forge:furo
  - dataclasses
  - pyproj
  - scipy
  - pandas
