name: borea
channels:
 - conda-forge
dependencies:
  - python==3.8.*
  - gdal
  - numpy
  - pylint
  - pytest
  - conda-forge:pytest-shutil
  - flake8
  - sphinx
  - conda-forge:furo
  - dataclasses
  - pyproj
  - scipy
  - pandas
  - build
  - twine
