name: Lint_python

on:
  push:
    branches: [main]
    tags:
  pull_request:

jobs:
  lint_python:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v1
      with:
        python-version: 3.10

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint flake8

    - name: Analysing the code with pylint
      run: |
        pylint pink_lady.py code/reader.py code/shot.py code/worksite.py code/writer.py

      continue-on-error: true

    - name: Analysing the code with flake8
      run: |
        flake8  --max-line-length 100 pink_lady.py code/reader.py code/shot.py code/worksite.py code/writer.py

