name: Lint_python

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint_python:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v1
      with:
        python-version: 3.10.13
        architecture: 'x64'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install gdal-bin libgdal-dev
        python -m pip install --upgrade pip
        export CPLUS_INCLUDE_PATH=/usr/include/gdal
        export C_INCLUDE_PATH=/usr/include/gdal
        pip install GDAL==3.4.1
        pip install -r ./requirements.txt

    - name: Analysing the code with pylint
      run: |
        pylint opk_to_opk.py opk_control.py
        pylint src/parser/parser_opk/args_read_opk.py src/parser/parser_opk/args_write_opk.py src/parser/args_control.py
        pylint src/geodesy/proj_engine.py src/geodesy/euclidean_proj.py src/geodesy/transform_geodesy.py
        pylint src/reader/reader_camera.py src/reader/reader_co_points.py src/reader/reader_gcp.py src/reader/reader_ground_img_pts.py
        pylint src/reader/orientation/manage_reader.py src/reader/orientation/reader_opk.py
        pylint src/datastruct/shot.py src/datastruct/gcp.py src/datastruct/workdata.py src/datastruct/camera.py src/datastruct/dtm.py
        pylint src/writer/writer_opk.py src/writer/manage_writer.py
        pylint src/utils/change_dim.py src/utils/check/check_args_opk.py src/utils/check/check_array.py src/utils/singleton/singleton.py
        pylint src/worksite/worksite.py
        pylint src/transform_world_image/transform_worksite/world_image_work.py src/transform_world_image/transform_worksite/image_world_work.py
        pylint src/transform_world_image/transform_worksite/image_world_intersection.py src/transform_world_image/transform_worksite/image_world_least_square.py
        pylint src/transform_world_image/transform_shot/world_image_shot.py src/transform_world_image/transform_shot/image_world_shot.py src/transform_world_image/transform_shot/conversion_coor_shot.py src/transform_world_image/transform_shot/space_resection.py
        pylint src/transform_world_image/transform_dtm/world_image_dtm.py
        pylint src/stat/statistics.py
        pylint src/math/sparse.py src/math/param_bundle.py

    - name: Analysing the code with flake8
      run: |
        flake8  --max-line-length 100 opk_to_opk.py opk_control.py
        flake8  --max-line-length 100 src/parser/parser_opk/args_read_opk.py src/parser/parser_opk/args_write_opk.py src/parser/args_control.py
        flake8  --max-line-length 100 src/geodesy/proj_engine.py src/geodesy/euclidean_proj.py src/geodesy/transform_geodesy.py
        flake8  --max-line-length 100 src/reader/reader_camera.py src/reader/reader_co_points.py src/reader/reader_gcp.py src/reader/reader_ground_img_pts.py
        flake8  --max-line-length 100 src/reader/orientation/manage_reader.py src/reader/orientation/reader_opk.py
        flake8  --max-line-length 100 src/datastruct/shot.py src/datastruct/gcp.py src/datastruct/workdata.py src/datastruct/camera.py src/datastruct/dtm.py
        flake8  --max-line-length 100 src/writer/writer_opk.py src/writer/manage_writer.py
        flake8  --max-line-length 100 src/utils/change_dim.py src/utils/check/check_args_opk.py src/utils/check/check_array.py src/utils/singleton/singleton.py
        flake8  --max-line-length 100 src/worksite/worksite.py
        flake8  --max-line-length 100 src/transform_world_image/transform_worksite/world_image_work.py src/transform_world_image/transform_worksite/image_world_work.py
        flake8  --max-line-length 100 src/transform_world_image/transform_shot/world_image_shot.py src/transform_world_image/transform_shot/image_world_shot.py src/transform_world_image/transform_shot/conversion_coor_shot.py src/transform_world_image/transform_shot/space_resection.py
        flake8  --max-line-length 100 src/transform_world_image/transform_worksite/image_world_intersection.py src/transform_world_image/transform_worksite/image_world_least_square.py
        flake8  --max-line-length 100 src/transform_world_image/transform_dtm/world_image_dtm.py
        flake8  --max-line-length 100 src/stat/statistics.py
        flake8  --max-line-length 100 src/math/sparse.py src/math/param_bundle.py
