name: Lint_python

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint_python:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install gdal-bin libgdal-dev
        python -m pip install --upgrade pip
        export CPLUS_INCLUDE_PATH=/usr/include/gdal
        export C_INCLUDE_PATH=/usr/include/gdal
        pip install GDAL==3.4.1
        pip install -r ./dependency/requirements.txt

    - name: Analysing the code with pylint
      run: |
        pylint opk_to_opk.py opk_control.py opk_to_rpc.py pt_image_to_world.py pt_world_to_image.py ptfile_image_to_world.py ptfile_world_to_image.py spaceresection_opk.py opk_to_conical.py
        pylint src/parser/parser_format/args_read_opk.py src/parser/parser_format/args_write_opk.py src/parser/parser_format/args_write_rpc.py src/parser/parser_format/args_write_con.py
        pylint src/parser/parser_func/args_control.py src/parser/parser_func/args_image_world.py src/parser/parser_func/args_world_image.py src/parser/parser_func/args_spaceresection.py
        pylint src/parser/parser_adata/args_write.py src/parser/parser_adata/args_gen_param.py src/parser/parser_adata/args_unit_shot.py src/parser/parser_adata/args_add_shot.py src/parser/parser_adata/args_pt2d.py src/parser/parser_adata/args_pt3d.py src/parser/parser_adata/args_file_gcp2d.py src/parser/parser_adata/args_file_gcp3d.py
        pylint src/geodesy/proj_engine.py src/geodesy/euclidean_proj.py src/geodesy/transform_geodesy.py src/geodesy/approx_euclidean_proj.py src/geodesy/local_euclidean_proj.py
        pylint src/reader/reader_camera.py src/reader/reader_point.py
        pylint src/reader/orientation/manage_reader.py src/reader/orientation/reader_opk.py
        pylint src/datastruct/shot.py src/datastruct/gcp.py src/datastruct/workdata.py src/datastruct/camera.py src/datastruct/dtm.py
        pylint src/writer/writer_opk.py src/writer/manage_writer.py src/writer/writer_rpc.py src/writer/writer_df_to_txt.py src/writer/writer_con.py
        pylint src/utils/check/check_args_opk.py src/utils/check/check_array.py src/utils/singleton/singleton.py src/utils/check/check_args_reader_pt.py src/utils/check/check_header.py src/utils/check/check_order_axe.py src/utils/xml/xml.py
        pylint src/worksite/worksite.py
        pylint src/transform_world_image/transform_worksite/world_image_work.py src/transform_world_image/transform_worksite/image_world_work.py
        pylint src/transform_world_image/transform_worksite/image_world_intersection.py src/transform_world_image/transform_worksite/image_world_least_square.py src/transform_world_image/transform_worksite/space_resection.py
        pylint src/transform_world_image/transform_shot/world_image_shot.py src/transform_world_image/transform_shot/image_world_shot.py src/transform_world_image/transform_shot/conversion_coor_shot.py
        pylint src/transform_world_image/transform_dtm/world_image_dtm.py
        pylint src/stat/statistics.py
        pylint src/utils/miscellaneous/sparse.py src/utils/miscellaneous/param_bundle.py src/utils/miscellaneous/miscellaneous.py
        pylint src/format/rpc.py src/format/conical.py
        pylint src/rsc/search_proj.py

    - name: Analysing the code with flake8
      run: |
        flake8  --max-line-length 100 opk_to_opk.py opk_control.py opk_to_rpc.py pt_image_to_world.py pt_world_to_image.py ptfile_image_to_world.py ptfile_world_to_image.py spaceresection_opk.py opk_to_conical.py
        flake8  --max-line-length 100 src/parser/parser_format/args_read_opk.py src/parser/parser_format/args_write_opk.py src/parser/parser_format/args_write_rpc.py src/parser/parser_format/args_write_con.py
        flake8  --max-line-length 100 src/parser/parser_func/args_control.py src/parser/parser_func/args_image_world.py src/parser/parser_func/args_world_image.py src/parser/parser_func/args_spaceresection.py
        flake8  --max-line-length 100 src/parser/parser_adata/args_write.py src/parser/parser_adata/args_gen_param.py src/parser/parser_adata/args_unit_shot.py src/parser/parser_adata/args_add_shot.py src/parser/parser_adata/args_pt2d.py src/parser/parser_adata/args_pt3d.py src/parser/parser_adata/args_file_gcp2d.py src/parser/parser_adata/args_file_gcp3d.py
        flake8  --max-line-length 100 src/geodesy/proj_engine.py src/geodesy/euclidean_proj.py src/geodesy/transform_geodesy.py src/geodesy/approx_euclidean_proj.py src/geodesy/local_euclidean_proj.py
        flake8  --max-line-length 100 src/reader/reader_camera.py src/reader/reader_point.py
        flake8  --max-line-length 100 src/reader/orientation/manage_reader.py src/reader/orientation/reader_opk.py
        flake8  --max-line-length 100 src/datastruct/shot.py src/datastruct/gcp.py src/datastruct/workdata.py src/datastruct/camera.py src/datastruct/dtm.py
        flake8  --max-line-length 100 src/writer/writer_opk.py src/writer/manage_writer.py src/writer/writer_rpc.py src/writer/writer_df_to_txt.py src/writer/writer_con.py
        flake8  --max-line-length 100 src/utils/check/check_args_opk.py src/utils/check/check_array.py src/utils/singleton/singleton.py src/utils/check/check_args_reader_pt.py src/utils/check/check_header.py src/utils/check/check_order_axe.py src/utils/xml/xml.py
        flake8  --max-line-length 100 src/worksite/worksite.py
        flake8  --max-line-length 100 src/transform_world_image/transform_worksite/world_image_work.py src/transform_world_image/transform_worksite/image_world_work.py src/transform_world_image/transform_worksite/space_resection.py
        flake8  --max-line-length 100 src/transform_world_image/transform_shot/world_image_shot.py src/transform_world_image/transform_shot/image_world_shot.py src/transform_world_image/transform_shot/conversion_coor_shot.py
        flake8  --max-line-length 100 src/transform_world_image/transform_worksite/image_world_intersection.py src/transform_world_image/transform_worksite/image_world_least_square.py
        flake8  --max-line-length 100 src/transform_world_image/transform_dtm/world_image_dtm.py
        flake8  --max-line-length 100 src/stat/statistics.py
        flake8  --max-line-length 100 src/utils/miscellaneous/sparse.py src/utils/miscellaneous/param_bundle.py src/utils/miscellaneous/miscellaneous.py
        flake8  --max-line-length 100 src/format/rpc.py src/format/conical.py
        flake8  --max-line-length 100 src/rsc/search_proj.py
