name: Lint_python

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint_python:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v1
      with:
        python-version: 3.10.13
        architecture: 'x64'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install gdal-bin libgdal-dev
        python -m pip install --upgrade pip
        export CPLUS_INCLUDE_PATH=/usr/include/gdal
        export C_INCLUDE_PATH=/usr/include/gdal
        pip install pylint flake8 numpy importlib dataclasses pyproj scipy jsons wheel GDAL==3.4.1

    - name: Analysing the code with pylint
      run: |
        pylint pink_lady.py src/geodesy/proj_engine.py src/geodesy/euclidean_proj.py src/reader/reader_camera.py src/reader/reader_copoints.py src/reader/reader_gcp.py src/reader/orientation/manage_reader.py src/reader/orientation/reader_opk.py src/datastruct/shot.py src/datastruct/gcp.py src/datastruct/worksite.py src/datastruct/camera.py src/writer/writer_opk.py src/writer/manage_writer.py src/utils/conversion.py src/utils/check_header.py src/position/shot_pos.py src/position/copoints_pos.py src/stat/statistics.py src/altimetry/dem.py

    - name: Analysing the code with flake8
      run: |
        flake8  --max-line-length 100 pink_lady.py src/geodesy/proj_engine.py src/geodesy/euclidean_proj.py src/reader/reader_camera.py src/reader/reader_copoints.py src/reader/reader_gcp.py src/reader/orientation/manage_reader.py src/reader/orientation/reader_opk.py src/datastruct/shot.py src/datastruct/gcp.py src/datastruct/worksite.py src/datastruct/camera.py src/writer/writer_opk.py src/writer/manage_writer.py src/utils/conversion.py src/utils/check_header.py src/position/shot_pos.py src/position/copoints_pos.py src/stat/statistics.py src/altimetry/dem.py
