name: Lint_python

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint_python:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install gdal-bin libgdal-dev
        python -m pip install --upgrade pip
        export CPLUS_INCLUDE_PATH=/usr/include/gdal
        export C_INCLUDE_PATH=/usr/include/gdal
        pip install GDAL==3.4.1
        pip install -r ./dependency/requirements.txt

    - name: Analysing the code with pylint
      run: |
        pylint ./borea/
        pylint ./borea_tools/
        pylint ./test/*/
        pylint ./examples/

    - name: Analysing the code with flake8
      run: |
        flake8  --max-line-length 100 ./borea/
        flake8  --max-line-length 100 ./borea_tools/
        flake8  --max-line-length 100 ./test/
        flake8  --max-line-length 100 ./examples/
