name: unitary_test

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout branch
      uses: actions/checkout@v4
    
    - name: Install environment
      run: |
        sudo apt-get install libgdal-dev==3.4.1
        python -m pip install --upgrade pip
        pip install numpy pylint pytest pytest-shutil flake8 sphinx furo importlib dataclasses jsons pyproj scipy GDAL==3.4.1

    - name: Run tests with pytest
      run: python3 -m pytest -s ./test -v
