name: unitary_test

on:
  pull_request:
    branches: 
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout branch
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-shutil

    - name: Run tests with pytest
      uses: actions/checkout@v4
      with:
        environment-file: environment.yml
      run: python3 -m pytest -s ./test -v
