name: test_windows

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: windows-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout branch
      uses: actions/checkout@v4
    
    - name: Install environment
      uses: mamba-org/setup-micromamba@v1.4.3
      with:
        environment-file: environment.yml
        environment-name: pink_lady
        cache-environment: true
        cache-downloads: true
        init-shell: bash

    - name: Run unit tests with pytest
      shell: bash -el {0}
      run: python -m pytest -s ./test -v

    - name: Run regression test conv opk
      shell: bash -el {0}
      run: python ./opk_to_opk.py -r ./dataset/23FD1305_alt_test.OPK -i "N X Y Z O P K C" -f 2 -e 2154 -j ./dataset/proj.json -y ./dataset/ -c ./dataset/Camera1.txt -m ./dataset/MNT_France_25m_h_crop.tif --fm height -n Test -w ./test/tmp/ -o "N X Y H P O K C" -d radian -l False

    - name: Run regression test control opk
      shell: bash -el {0}
      run: python ./opk_control.py -r ./dataset/23FD1305_alt_test.OPK -i "N X Y Z O P K C" -f 2 -c ./dataset/Camera1.txt -e 2154 -j ./dataset/proj.json -y ./dataset/ -m ./dataset/MNT_France_25m_h_crop.tif --fm height -t ./dataset/terrain_test.mes -g ./dataset/GCP_test.app -d 13 --fg height -p inter -w ./test/tmp/

    - name: Run regression test opk to rpc
      shell: bash -el {0}
      run: python ./opk_to_rpc.py -r ./dataset/23FD1305_alt_test.OPK -i "N X Y Z O P K C" -f 2 -c ./dataset/Camera1.txt -e 2154 -j ./dataset/proj.json -y ./dataset/ -m ./dataset/MNT_France_25m_h_crop.tif --fm height -o 3
