name: unitary_test

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout branch
      uses: actions/checkout@v4
    
    - name: Install environment
      uses: mamba-org/setup-micromamba@v1.4.3
      with:
        environment-file: environment.yml

    - name: Run tests with pytest
      run: python3 -m pytest -s ./test -v
